### ISSUE TITLE
Arbitrum is incorrectly showing as down on the dashboard

### ISSUE THREAD

**Issue by jumpsiegel** [wormhole-foundation/wormhole-dashboard#47]
## Expected Behavior

It should only show as down if the guardian is 1500 blocks behind

## Current Behavior

It currently shows as down if the guardian is 1000 blocks behind

**Comment by kev1n-peters** [comment]
This is also happening to Optimism. We should probably add a function like `getBehindDiffForChain` that returns the `BEHIND_DIFF` per chain
